### ISSUE TITLE
Retrieve data from API for a movie

### ISSUE THREAD

**Issue by OwenM4** [passiondynamics/cast-le#12]
**Points:** 3

**TODOs:**
- [x] Create a method to calculate the four most popular actors in a movie
- [x] Get the four most popular actors for a movie
- [x] Get the actor's pictures
- [x] Get other possible answers for this movie (this may be as simple as getting the related movies from the API if that is not the case this should spin off into its own issue)
- [x] Test Methods

**Description:** Get all the information needed to run the game from the API using the movie titles.

**Notes:** We need to get all of this information from the API or we will not be able to run the game. We can complete this after getting the movie titles and add all this information into the database.
Depends on https://github.com/passiondynamics/cast-le-backend/issues/11
